#!/system/bin/sh
# www/start-httpd.sh — starts busybox httpd for Dikec Control Panel
#
# service.sh calls this via supervisor_loop; may also be run directly.
# Reads /data/dikec/conf/lan_expose:
#   0 (default) — bind 127.0.0.1:8088, token-only auth in api.cgi
#   1           — bind 0.0.0.0:8088, HTTP basic-auth + token (defense-in-depth)
#
# The runtime httpd.conf is written to $DCP_DATA each start so that
# the LAN-mode basic-auth password stays in sync with the panel_token.

BB=/data/adb/modules/bin-utils/system/bin/busybox
DCP=/data/adb/modules/dikec-control-panel
DCP_DATA=/data/dikec

mkdir -p "$DCP_DATA/logs" "$DCP_DATA/conf"

LAN_EXPOSE=$(cat "$DCP_DATA/conf/lan_expose" 2>/dev/null | tr -d '[:space:]' || printf '0')
PANEL_TOKEN=$(cat "$DCP_DATA/conf/panel_token" 2>/dev/null | tr -d '\r\n' || printf '')

# Build runtime httpd.conf (base + optional auth)
RUNTIME_CONF="$DCP_DATA/httpd-runtime.conf"
{
    printf '# Generated by start-httpd.sh — do not edit\n'
    printf 'I:index.html\n'
} > "$RUNTIME_CONF"

if [ "$LAN_EXPOSE" = "1" ] && [ -n "$PANEL_TOKEN" ]; then
    BIND="0.0.0.0:8088"
    # HTTP basic-auth: first layer of defence (api.cgi also checks token)
    # busybox httpd.conf format: A:<path>:<user>:<crypt_or_plain_pass>
    # Use MD5-crypt hash so the plaintext token isn't stored in the conf file.
    _HASH=$("$BB" httpd -m "$PANEL_TOKEN" 2>/dev/null)
    _PASS="${_HASH:-$PANEL_TOKEN}"        # fall back to plaintext if -m fails
    printf 'A:/:dikec:%s\n' "$_PASS" >> "$RUNTIME_CONF"
    printf '[start-httpd] LAN mode: binding 0.0.0.0:8088 with basic-auth\n'
else
    BIND="127.0.0.1:8088"
    printf '[start-httpd] localhost mode: binding 127.0.0.1:8088\n'
fi

# -f: foreground (supervisor_loop / caller manages the process lifecycle)
exec "$BB" httpd -f -p "$BIND" -h "$DCP/www" -c "$RUNTIME_CONF"
